# Generated by Django 4.1.4 on 2023-02-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="blocked_user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="following",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="panding_request",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="private_account",
        ),
    ]
