# Generated by Django 3.2.18 on 2023-03-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aogorder',
            name='service_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.aogservice'),
        ),
    ]
