# Generated by Django 4.1.4 on 2023-02-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuffs", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aogorder",
            name="order_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="aogorder",
            name="order_items",
            field=models.ManyToManyField(to="stuffs.aog"),
        ),
        migrations.AddField(
            model_name="aogorder",
            name="order_tech",
            field=models.CharField(
                choices=[("offloading", "Offloading"), ("onloading", "Onloading")],
                default="offloading",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aogorder",
            name="subject",
            field=models.CharField(default="", max_length=155, verbose_name="Subject"),
        ),
    ]
