# Generated by Django 4.1.7 on 2023-02-26 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(default='', max_length=6, verbose_name='Flight')),
                ('sched_date', models.DateField(blank=True, null=True, verbose_name='Schedule date')),
                ('sched_time', models.TimeField(blank=True, null=True, verbose_name='Schedule time')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FlightProject',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('project_date', models.DateField(verbose_name='Date')),
                ('project_name', models.CharField(max_length=355, verbose_name='Project name')),
                ('technology', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure'), ('connection', 'Connection')], default='', max_length=15, verbose_name='Tech')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('inprogress', 'InProgress'), ('canceled', 'Canceled'), ('standBy', 'StandBy')], default='draft', max_length=15, verbose_name='Status')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='projects.tag')),
            ],
            options={
                'verbose_name': 'FlightProject',
                'verbose_name_plural': 'FlightProjects',
                'ordering': ('-status',),
            },
        ),
    ]
