# Generated by Django 3.2.18 on 2023-03-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_airport'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_station', to='directory.airport'),
        ),
    ]
