# Generated by Django 4.1.7 on 2023-02-26 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightproject',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.flightproject'),
        ),
    ]
