# Generated by Django 4.1.4 on 2023-01-13 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='share_to',
            field=models.ManyToManyField(related_name='share_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
