# Generated by Django 4.1.4 on 2023-01-13 18:33

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_note_slug_note_tags_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.category'),
        ),
    ]
