# Generated by Django 3.2.18 on 2023-03-21 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AogService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('00-onload', 'Onload'), ('10-offload', 'Offload')], default='10-offload', max_length=20, verbose_name='type')),
                ('data_createAt', models.DateTimeField(auto_now=True, verbose_name='DateTime created')),
                ('data_updateAt', models.DateTimeField(auto_now_add=True, verbose_name='DateTime updated')),
                ('request_date', models.DateField(auto_now=True, verbose_name='Service date')),
                ('service_name', models.CharField(max_length=50, verbose_name='Service name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Request AOG handling',
            },
        ),
        migrations.CreateModel(
            name='DutyPerson',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('position', models.CharField(max_length=50, verbose_name='Person position')),
                ('contact_phone', models.CharField(max_length=12, verbose_name='Contact Phone')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.aogservice')),
            ],
            options={
                'verbose_name': 'Responsble person',
                'verbose_name_plural': 'Responsibles',
            },
        ),
    ]
