# Generated by Django 4.1.4 on 2023-02-14 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0001_initial"),
        ("agents", "0001_initial"),
        ("stuffs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AogService",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("00-onload", "Onload"), ("10-offload", "Offload")],
                        default="10-offload",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "data_createAt",
                    models.DateTimeField(
                        auto_now=True, verbose_name="DateTime created"
                    ),
                ),
                (
                    "data_updateAt",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="DateTime updated"
                    ),
                ),
                (
                    "request_date",
                    models.DateField(auto_now=True, verbose_name="Service date"),
                ),
                (
                    "service_name",
                    models.CharField(max_length=50, verbose_name="Service name"),
                ),
                (
                    "fix_required",
                    models.BooleanField(default=False, verbose_name="Fix on board"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("aog_item", models.ManyToManyField(to="stuffs.aog")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_created",
                        to="agents.agent",
                        verbose_name="created by",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aog_from_flight",
                        to="schedules.regularscheduler",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DutyPerson",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "full_name",
                    models.CharField(max_length=50, verbose_name="Full Name"),
                ),
                (
                    "position",
                    models.CharField(max_length=50, verbose_name="Person position"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=12, verbose_name="Contact Phone"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.aogservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users persons stuff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsble person",
                "verbose_name_plural": "Responsibles",
            },
        ),
        migrations.AddField(
            model_name="aogservice",
            name="responsibles_persons",
            field=models.ManyToManyField(to="services.dutyperson"),
        ),
        migrations.AddIndex(
            model_name="aogservice",
            index=models.Index(fields=["-type"], name="service_priority_idx"),
        ),
    ]
