# Generated by Django 4.1.7 on 2023-02-26 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('schedules', '0001_initial'),
        ('stuffs', '0001_initial'),
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyperson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users persons stuff'),
        ),
        migrations.AddField(
            model_name='aogservice',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_services_request', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='aogservice',
            name='aog_item',
            field=models.ManyToManyField(to='stuffs.aog'),
        ),
        migrations.AddField(
            model_name='aogservice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_created', to='agents.agent', verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='aogservice',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aog_from_flight', to='schedules.regularscheduler'),
        ),
        migrations.AddIndex(
            model_name='aogservice',
            index=models.Index(fields=['-type'], name='service_priority_idx'),
        ),
    ]
