# Generated by Django 4.1.7 on 2023-02-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_airline_arrival_departure_flight_schedule'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aogservice',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aog_from_flight', to='schedules.schedule'),
        ),
    ]
