# Generated by Django 4.1.4 on 2023-01-10 19:48

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wrhs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DClass',
            new_name='DGRClass',
        ),
        migrations.AlterUniqueTogether(
            name='dcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wrhs.dcategory', verbose_name='Subdivision'),
        ),
        migrations.AlterUniqueTogether(
            name='dcategory',
            unique_together={('parent', 'slug')},
        ),
        migrations.RemoveField(
            model_name='dcategory',
            name='subdivision',
        ),
    ]
