# Generated by Django 4.1.4 on 2023-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrhs', '0003_alter_dgrclass_imp_code2_alter_dgrclass_imp_code3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgrclass',
            name='imp_code2',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='IMP Code2'),
        ),
        migrations.AlterField(
            model_name='dgrclass',
            name='imp_code3',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='IMP Code3'),
        ),
    ]
