# Generated by Django 4.1.4 on 2023-01-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrhs", "0004_alter_dgrclass_imp_code2_alter_dgrclass_imp_code3"),
    ]

    operations = [
        migrations.AddField(
            model_name="dcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
