# Generated by Django 4.1.4 on 2023-01-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrhs", "0005_dcategory_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="dgrclass",
            name="cao",
            field=models.BooleanField(default=False, verbose_name="CAO"),
        ),
    ]
