# Generated by Django 4.1.4 on 2023-01-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_directory', '0002_impcode_description'),
        ('wrhs', '0006_dgrclass_cao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dgrclass',
            name='imp_code1',
        ),
        migrations.RemoveField(
            model_name='dgrclass',
            name='imp_code2',
        ),
        migrations.RemoveField(
            model_name='dgrclass',
            name='imp_code3',
        ),
        migrations.AddField(
            model_name='dgrclass',
            name='imp_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base_directory.impcode', verbose_name='drg_imp_code'),
        ),
    ]
