# Generated by Django 4.1.4 on 2023-01-16 13:54

import apps.flight_schedule.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0002_alter_airline_arl_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='flight_schedule.docscategory')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=apps.flight_schedule.models.TaskAttachments.task_attachments_directory_path)),
                ('description', models.CharField(max_length=155)),
                ('content', tinymce.models.HTMLField(blank=True, default='')),
                ('createAt', models.DateTimeField(auto_now=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
                ('category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flight_schedule.docscategory')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='flight_schedule.tag')),
            ],
        ),
        migrations.CreateModel(
            name='FlightTask',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('task_date', models.DateField(verbose_name='Date')),
                ('technology', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure')], default='', max_length=15, verbose_name='Tech')),
                ('flight', models.CharField(default='', max_length=6, verbose_name='Flight')),
                ('sched_time', models.TimeField(blank=True, null=True, verbose_name='Schedule time')),
                ('payload', models.CharField(default='', max_length=50, verbose_name='Payload(kg)')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('inprogress', 'InProgress'), ('canceled', 'Canceled'), ('standBy', 'StandBy')], default='draft', max_length=15, verbose_name='Status')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_airline', to='directory.airline')),
                ('docs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flight_schedule.taskattachments')),
                ('payload_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payload.payload')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_register', to='directory.register')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_station', to='directory.station')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='flight_schedule.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FlightTask',
                'verbose_name_plural': 'FlightTasks',
                'ordering': ('-status',),
            },
        ),
    ]
