# Generated by Django 4.1.4 on 2023-01-08 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flight_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docscategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='flight_schedule.docscategory'),
        ),
        migrations.AlterUniqueTogether(
            name='docscategory',
            unique_together={('parent', 'slug')},
        ),
    ]
