# Generated by Django 4.0.10 on 2023-03-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwbAirlineCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Airline name')),
                ('iataCode', models.CharField(blank=True, max_length=2, null=True, verbose_name='Iata code')),
                ('awb_prefix', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=155, null=True, verbose_name='Country')),
            ],
        ),
    ]
