# Generated by Django 3.2.18 on 2023-03-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwbAirlineCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Airline name')),
                ('iataCode', models.CharField(blank=True, max_length=2, null=True, verbose_name='Iata code')),
                ('awb_prefix', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=155, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Airline code',
                'verbose_name_plural': 'Airline codes',
            },
        ),
        migrations.CreateModel(
            name='ShcMsgAbbr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=155, null=True, verbose_name='Type')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Message code',
                'verbose_name_plural': 'Message codes',
            },
        ),
    ]
