# Generated by Django 4.0.10 on 2023-03-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShcMsgAbbr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=155, null=True, verbose_name='Type')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Message code',
                'verbose_name_plural': 'Message codes',
            },
        ),
        migrations.AlterModelOptions(
            name='awbairlinecode',
            options={'verbose_name': 'Airline code', 'verbose_name_plural': 'Airline codes'},
        ),
    ]
