# Generated by Django 4.1.4 on 2023-01-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SITA MESSAGE_CARGO', 'SITA MESSAGE_CARGO'), ('TRANSPORT MESSAGES', 'TRANSPORT MESSAGES'), ('COMMERCIAL MESSAGES', 'COMMERCIAL MESSAGES'), ('IATA_CARGO_IMP_SUPPORT', 'IATA_CARGO_IMP_SUPPORT'), ('IATA_PADIS_SUPPORT', 'IATA_PADIS_SUPPORT'), ('SPECIAL HANDLING CODES', 'SPECIAL HANDLING CODES'), ('DGR IMP CODES', 'DGR IMP CODES')], max_length=60, verbose_name='Type')),
                ('code', models.CharField(max_length=7, verbose_name='Type')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Description')),
            ],
        ),
    ]
