# Generated by Django 4.1.4 on 2023-01-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impcode',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Description'),
        ),
    ]
