# Generated by Django 4.1.4 on 2023-02-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(default="", max_length=50, verbose_name="Name"),
        ),
    ]
