# Generated by Django 4.1.7 on 2023-02-26 23:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='Store location name ')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_wrhs', to='agents.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item weight')),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('item_lenght', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item lenght')),
                ('item_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item width')),
                ('item_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item height')),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('is_serviceable', models.BooleanField(default=True, verbose_name='Is Serviceable?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/instr')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_instruments', to='agents.agent')),
                ('location_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stuffs.storelocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aog',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item weight')),
                ('item_lenght', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item lenght')),
                ('item_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item width')),
                ('item_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item height')),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('is_serviceable', models.BooleanField(default=True, verbose_name='Is Serviceable?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/aog')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_aogs', to='agents.agent')),
                ('location_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stuffs.storelocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcStand',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item weight')),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('item_lenght', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item lenght')),
                ('item_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item width')),
                ('item_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item height')),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('is_serviceable', models.BooleanField(default=True, verbose_name='Is Serviceable?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/stands')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_acstands', to='agents.agent')),
                ('location_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stuffs.storelocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcEngine',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item')),
                ('item_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item weight')),
                ('item_serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial number')),
                ('item_part_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Part number')),
                ('item_lenght', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item lenght')),
                ('item_width', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item width')),
                ('item_height', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item height')),
                ('image_document', models.FileField(blank=True, null=True, upload_to='')),
                ('is_serviceable', models.BooleanField(default=True, verbose_name='Is Serviceable?')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stuffs/engins')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_acengines', to='agents.agent')),
                ('location_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stuffs.storelocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
