# Generated by Django 4.1.4 on 2023-01-05 23:42

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('aircraftblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='aircraftblog.category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
        migrations.AddField(
            model_name='aircraftitem',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraftblog.manufacturer', verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='aircraftitem',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aircraftblog.category'),
        ),
        migrations.AddField(
            model_name='aircraftitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='aircraftblog.tag'),
        ),
    ]
