# Generated by Django 4.1.4 on 2023-01-17 23:06

import apps.directory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(default='', max_length=2, verbose_name='Iata')),
                ('icao', models.CharField(default='', max_length=3, verbose_name='Icao')),
                ('rus_code', models.CharField(default='', max_length=2, verbose_name='Rus')),
                ('comment_eng', models.CharField(default='', max_length=85, verbose_name='Description eng')),
                ('comment_rus', models.CharField(default='', max_length=85, verbose_name='Description rus')),
                ('country', models.CharField(default='', max_length=85, verbose_name='Country')),
                ('alliance', models.CharField(default='', max_length=5, verbose_name='Alliance')),
                ('lowcost', models.CharField(default='', max_length=1, verbose_name='Lowcost')),
                ('description', models.CharField(default='', max_length=50, verbose_name='Description')),
                ('arl_logo', models.ImageField(blank=True, null=True, upload_to=apps.directory.models.airline_logo_directory_path)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to=apps.directory.models.airline_banner_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=5, verbose_name='Number')),
                ('ac_type', models.CharField(default='', max_length=3, verbose_name='Type')),
                ('co', models.CharField(default='', max_length=5, verbose_name='Company')),
                ('mod', models.CharField(default='', max_length=4, verbose_name='Modification')),
                ('g_type', models.CharField(default='', max_length=5, verbose_name='G_TYPE')),
                ('description', models.CharField(default='', max_length=50, verbose_name='Description')),
                ('ac_photo', models.ImageField(blank=True, null=True, upload_to=apps.directory.models.register_photo_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(default='', max_length=3, verbose_name='IATA')),
                ('icao', models.CharField(default='', max_length=4, verbose_name='ICAO')),
                ('rus', models.CharField(default='', max_length=5, verbose_name='Rus')),
                ('comment_eng', models.CharField(default='', max_length=50, verbose_name='Comment Eng')),
                ('comment_rus', models.CharField(default='', max_length=50, verbose_name='Comment Rus')),
                ('country', models.CharField(default='', max_length=50, verbose_name='Country')),
                ('city_r', models.CharField(default='', max_length=50, verbose_name='Sity R')),
                ('airport_e', models.CharField(default='', max_length=50, verbose_name='Airport E')),
                ('region', models.CharField(default='', max_length=50, verbose_name='Region')),
                ('airport_r', models.CharField(default='', max_length=50, verbose_name='Airport R')),
                ('city_e', models.CharField(default='', max_length=50, verbose_name='City E')),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to=apps.directory.models.station_flag_directory_path)),
            ],
        ),
    ]
