# Generated by Django 3.2.18 on 2023-03-13 05:55

import apps.directory.models.airline
import apps.directory.models.register
import apps.directory.models.airports
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageFleet', models.IntegerField(null=True)),
                ('founding', models.IntegerField(null=True)),
                ('sizeAirline', models.IntegerField(null=True)),
                ('statusAirline', models.CharField(blank=True, default='', max_length=155, verbose_name='StatusAirline')),
                ('iataPrefixAccounting', models.IntegerField(null=True)),
                ('callsign', models.CharField(default='', max_length=155, verbose_name='Callsign')),
                ('codeHub', models.CharField(default='', max_length=5, verbose_name='CodeHUB')),
                ('codeIso2Country', models.CharField(blank=True, default='', max_length=4, verbose_name='CodeIso2Country')),
                ('codeIataAirline', models.CharField(default='', max_length=2, verbose_name='Iata')),
                ('codeIcaoAirline', models.CharField(default='', max_length=3, verbose_name='Icao')),
                ('nameAirline', models.CharField(blank=True, default='', max_length=85, verbose_name='Description eng')),
                ('nameCountry', models.CharField(blank=True, default='', max_length=85, null=True, verbose_name='Country')),
                ('type', models.CharField(blank=True, default='', max_length=155, verbose_name='Type')),
                ('arl_logo', models.ImageField(upload_to=apps.directory.models.airline.airline_image_path)),
                ('banner_img', models.ImageField(blank=True, null=True, upload_to=apps.directory.models.airline.airline_banner_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=5, verbose_name='Number')),
                ('ac_type', models.CharField(default='', max_length=3, verbose_name='Type')),
                ('co', models.CharField(default='', max_length=5, verbose_name='Company')),
                ('mod', models.CharField(default='', max_length=4, verbose_name='Modification')),
                ('g_type', models.CharField(default='', max_length=5, verbose_name='G_TYPE')),
                ('description', models.CharField(default='', max_length=50, verbose_name='Description')),
                ('ac_photo', models.ImageField(blank=True, null=True, upload_to=apps.directory.models.register.register_photo_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(default='', max_length=3, verbose_name='IATA')),
                ('icao', models.CharField(default='', max_length=4, verbose_name='ICAO')),
                ('rus', models.CharField(default='', max_length=5, verbose_name='Rus')),
                ('comment_eng', models.CharField(default='', max_length=50, verbose_name='Comment Eng')),
                ('comment_rus', models.CharField(default='', max_length=50, verbose_name='Comment Rus')),
                ('country', models.CharField(default='', max_length=50, verbose_name='Country')),
                ('city_r', models.CharField(default='', max_length=50, verbose_name='Sity R')),
                ('airport_e', models.CharField(default='', max_length=50, verbose_name='Airport E')),
                ('region', models.CharField(default='', max_length=50, verbose_name='Region')),
                ('airport_r', models.CharField(default='', max_length=50, verbose_name='Airport R')),
                ('city_e', models.CharField(default='', max_length=50, verbose_name='City E')),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to=apps.directory.models.airports.station_flag_directory_path)),
            ],
        ),
    ]
