# Generated by Django 3.2.18 on 2023-03-13 07:41

import apps.directory.models.airports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt', models.IntegerField(null=True)),
                ('codeIataAirport', models.CharField(default='', max_length=3, verbose_name='Airport IATA')),
                ('codeIcaoAirport', models.CharField(default='', max_length=4, verbose_name='Airport ICAO')),
                ('codeIataCity', models.CharField(default='', max_length=3, verbose_name='City IATA')),
                ('codeIso2Country', models.CharField(default='', max_length=2, verbose_name='ISO2Country')),
                ('latitudeAirport', models.DecimalField(decimal_places=7, max_digits=9)),
                ('longitudeAirport', models.DecimalField(decimal_places=7, max_digits=9)),
                ('nameAirport', models.CharField(blank=True, max_length=100, null=True, verbose_name='Airport name')),
                ('nameCountry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('timezone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone')),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to=apps.directory.models.airports.station_flag_directory_path)),
            ],
        ),
    ]
