# Generated by Django 3.2.18 on 2023-03-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_airport'),
        ('projects', '0003_alter_flight_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
