# Generated by Django 3.2.18 on 2023-03-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_delete_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='latitudeAirport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitudeAirport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
