# Generated by Django 3.2.18 on 2023-03-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20230313_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='latitudeAirport',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='longitudeAirport',
        ),
    ]
