# Generated by Django 3.2.18 on 2023-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20230313_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='latitudeAirport',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitudeAirport',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
