# Generated by Django 3.2.18 on 2023-03-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20230313_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='latitudeAirport',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='longitudeAirport',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=16, null=True),
        ),
    ]
