# Generated by Django 3.2.18 on 2023-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20230313_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='gmt',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
