# Generated by Django 4.1.7 on 2023-02-26 20:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegularScheduler',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('createAt', models.DateTimeField(auto_now=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True)),
                ('tech_rout', models.CharField(max_length=15, verbose_name='Tech')),
                ('flt_number', models.CharField(max_length=8, verbose_name='Flight number')),
                ('airport', models.CharField(max_length=3, verbose_name='Airport')),
                ('sta', models.TimeField(blank=True, null=True, verbose_name='STA')),
                ('pta', models.TimeField(blank=True, null=True, verbose_name='PTA')),
                ('ata', models.TimeField(blank=True, null=True, verbose_name='ATA')),
                ('std', models.TimeField(blank=True, null=True, verbose_name='STD')),
                ('ptd', models.TimeField(blank=True, null=True, verbose_name='PTD')),
                ('atd', models.TimeField(blank=True, null=True, verbose_name='ATD')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
