# Generated by Django 4.1.4 on 2023-01-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularscheduler',
            name='ata',
            field=models.TimeField(blank=True, null=True, verbose_name='ATA'),
        ),
        migrations.AlterField(
            model_name='regularscheduler',
            name='pta',
            field=models.TimeField(blank=True, null=True, verbose_name='PTA'),
        ),
        migrations.AlterField(
            model_name='regularscheduler',
            name='sta',
            field=models.TimeField(blank=True, null=True, verbose_name='STA'),
        ),
    ]
