# Generated by Django 4.1.4 on 2023-02-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_regularscheduler_ata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularscheduler',
            name='atd',
            field=models.TimeField(blank=True, null=True, verbose_name='ATA'),
        ),
        migrations.AddField(
            model_name='regularscheduler',
            name='ptd',
            field=models.TimeField(blank=True, null=True, verbose_name='ATA'),
        ),
        migrations.AddField(
            model_name='regularscheduler',
            name='std',
            field=models.TimeField(blank=True, null=True, verbose_name='ATA'),
        ),
    ]
