# Generated by Django 4.1.7 on 2023-02-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_aogservice_flight'),
        ('schedules', '0002_airline_arrival_departure_flight_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularScheduler',
        ),
        migrations.AddField(
            model_name='flight',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='departure',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='airline',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule'),
        ),
    ]
