# Generated by Django 4.1.4 on 2023-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_regularscheduler_ata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularscheduler',
            name='ata',
            field=models.TimeField(blank=True, null=True, verbose_name='ATA'),
        ),
        migrations.AlterField(
            model_name='regularscheduler',
            name='atd',
            field=models.TimeField(blank=True, null=True, verbose_name='ATD'),
        ),
        migrations.AlterField(
            model_name='regularscheduler',
            name='pta',
            field=models.TimeField(blank=True, null=True, verbose_name='PTA'),
        ),
        migrations.AlterField(
            model_name='regularscheduler',
            name='ptd',
            field=models.TimeField(blank=True, null=True, verbose_name='PTD'),
        ),
        migrations.AlterField(
            model_name='regularscheduler',
            name='sta',
            field=models.TimeField(blank=True, null=True, verbose_name='STA'),
        ),
        migrations.AlterField(
            model_name='regularscheduler',
            name='std',
            field=models.TimeField(blank=True, null=True, verbose_name='STD'),
        ),
    ]
