# Generated by Django 4.1.4 on 2023-01-17 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='Person Company LTD', max_length=50, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Phone')),
                ('mobile', models.CharField(blank=True, max_length=40, null=True, verbose_name='Mobile')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Address')),
                ('ogrn_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН')),
                ('inn_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН')),
                ('kpp_number', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
